# Generated by Django 6.1 on 2026-08-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='sales_notes',
            field=models.TextField(blank=True),
        ),
    ]
